import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Navbar, type NavItem } from '@/ui/organisms/Navbar';

const inter = Inter({ subsets: ['latin'] });

const links: NavItem[] = [
  {
    href: '/',
    label: 'Home',
    exact: true,
  },
  {
    href: '/products',
    label: 'All',
  },
];

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar links={links} />
        <main className="container mx-auto mt-12 px-4">{children}</main>
      </body>
    </html>
  );
}
